### ISSUE TITLE
Question 5 on Filter Form needs to be conditionally rendered before the Return

### ISSUE THREAD

**Issue by techhire-la** [techhire-la/questionnaire_react#6]
**A live version of the app can be found [here](https://ypi-referral-tool.herokuapp.com/catalogue)**

### The Issue

Question 5 renders one of three questions depending on the previous four questions and their responses.  Ideally, we want the logic of this condition to be played out after the `render` but before the `return`. However, whether it be due to nesting or some other factor, the question 5 classes that conditionally render which question 5 will show, will not pass down to the appropriate question.  The conditional statements are currently hardcoded into the questions themselves.  We would like to see the `render` logic work over the current hard coded render handled by a ternary operator in each question class. 

### Uhh... could you break that down?

Yeah, that was probably confusing.  So let's check out the code that I would ideally want to work.
In line 498 (subject to change) of FilterForm.js, you will find a commented out section labelled 'issue', with the following code

```javascript
        //////////////////  ISSUE  ///////////////////////////////////////////////
        var showAfterSchool = {display: 'none !important'};
        var showTraining = {display: 'none !important'};
        var showDiploma = {display: 'none !important'};

        if(this.state.questionNumber == '5') {

            showFive = {display: 'block !important'};

            debugger

            if (inSchool === 'true' && (levelOfEducation === 'No Highschool / Some Highschool' || levelOfEducation === 'Some College') ) {

                showAfterSchool = {display: 'block !important'};
                //
                // showTraining = {display: 'none !important'};
                // showDiploma = {display: 'none !important'};
            }

            else if (inSchool === 'false' && (levelOfEducation === 'No Highschool / Some Highschool') ) {
                showTraining = {display: 'block !important'};
                //
                // showAfterSchool = {display: 'none !important'};
                // showDiploma = {display: 'none !important'};
            }

            // (inSchool === 'false' && (levelOfEducation !== 'No Highschool / Some Highschool' || levelOfEducation !== 'Some College') )

            else {
                showDiploma= {display: 'block !important'};
                //
                // showAfterSchool = {display: 'none !important'};
                // showTraining = {display: 'none !important'};

            }

        }else{
            showFive = {display: 'none !important'};
            showAfterSchool = {display: 'none !important'};
            showTraining = {display: 'none !important'};
            showDiploma = {display: 'none !important'};
        }
```

The intention of this code is to handle the logic in the `render` however, probably due to some sort of nesting issue, the separate divs `showAfterSchool` , `showTraining` , and `showDiploma` do not seem to receive this class change.  

So, currently, the temporary fix coded in the return with a ternary operator in each one of question 5's classes.  See code block as follows:

```javascript
<div style={showFive} id="5" >

                        <div style={ (inSchool === 'true' && (levelOfEducation === 'No Highschool / Some Highschool' || levelOfEducation === 'Some College') ) ? {display: 'block'} : {display: 'none'} } >

                            <h3>Question 5</h3>
                            <h2> Is the participant looking for after-school program? </h2>

```
The div style of each question 5 should just be `<div style="showDiploma">` , `<div style="showTraining">`, and `<div style="showAfterSchool ">` respectively, so that when the variable names value is either `{display: 'none !important'};` or `{display: 'block !important'};`, the variables value with change accordingly.  

### Clarification

The issue of 5 is actually not the problem, it’s the questions that render under 5.  So the way the questionnaire works under every other question is that there is only one question included in the question number div.

E.G. *not real code*
```
<div id=“question-1”>
  <p>Who let the dogs out?</p>
</div>
```
However, because some of the questions previously answered are in direct conflict with later asked questions (e.g. If client is under 18, I don’t need to ask later if they are a veteran), other questions will not show up based on previous answers.  Question 5 can contain up to 3 questions conditionally rendered by previous answers and the problem seems to arise in that question 5 is a div and each one of the three questions is it’s own child div
e.g. *not real code*
```
<div id=“question-5”>
     <div class={showTraining}>
            Are you looking for vocational training?
    </div>
    <div class={showAfterSchool}>
          Are you looking for after school programs
    </div>
</div>
```
Those variables used in the class of child divs within div question 5 are not recieving their value changes based on the conditions of state

### Claiming this issue

Please be sure to comment on this issue request that you will be taking the task, ask any questions here (or slack), and keep a record of what you are doing as you progress.

**Comment by BeatrizTovar** [comment]
I took a look and I found some issues.
For each condition ` inSchool === 'true'`, _inSchool_ is undefined  therefore it should be `this.state.inSchool`, and it would also be better to use _true/false_ as a boolean rather than a string. 
Also, I believe for each variable such as `showAfterSchool = {display: 'block !important'}` there is no styling so even though each `<div>` is displaying there is technically nothing to display.
Hopefully this helps.

**Comment by JupiterLikeThePlanet** [comment]
Some clarifications, and this is my bad, but the code block that I have listed as ISSUE is the base code that should work, or rather, how I ideally want it to work.  However the code in the `return` has been altered so as to work with the existing code. So current code does work, but it may be missing things like the class names set in the ISSUE block

Also `inSchool` should be defined on line 372 as `var inSchool = this.state.inSchool;`

**Comment by JupiterLikeThePlanet** [comment]
Feel free to pull down the code, checkout out a new branch, and work on a solution.

**Comment by mhuynh1** [comment]
Can take up this issue if it's still open :)

As I understand it, there are 3 variations for question 5 and the one to be shown will depend on the values of inSchool and levelOfEducation.  And that logic should be handled before returning jsx. Is that the idea?

**Comment by techhire-la** [comment]
@mhuynh1 Bea currently has claim over the ticket and we are working on it now.  However, if there you wanted to do any styling, you can team up with @Arods642 and work on different portions of the app to style.  More tickets will be made and I will alert you to them as they come up

**Comment by techhire-la** [comment]
I have pulled Bea first PR.  Here are the updates.  Still working on Question 5 so task is not fully resolved.

### Refactor
All state handlers have been conformed into one function.  Now handleChange handles all state changes!
```
   handleChange = input => (e, {value}) => {
        debugger
        this.setState({[input]: value})
        console.log(input, value)
    }
```

### Question 5

Logic has been updated and state of inSchool is set to false instead of undefined.  
```
inSchool: false,
```

This is so that question 5 will appear so long as question 3 is answered.  However, this still does not resolve the problem.  However, code below, has improved upon the logic moving from return to render and here is what that looks like:
```
        let showLocation = questionNumber == '1' ? showDiv : hidden
        let showAge = questionNumber == '2' ? showDiv : hidden
        let showEducation = questionNumber == '3' ? showDiv : hidden
        let showInSchool = questionNumber == '4' ? showDiv : hidden
        

        let showFive = questionNumber == '5' ? showDiv : hidden
        let showA = (levelOfEducation === 'No Highschool / Some Highschool' || levelOfEducation === 'Some College') && (inSchool === 'true' || inSchool === true)  ? showDiv : hidden
        let showB = ( (levelOfEducation === 'Highschool/GED' || levelOfEducation === 'Some College' || levelOfEducation === 'AA' || levelOfEducation === 'BA or Higher') && (inSchool === 'false' || inSchool === false) )
        || (levelOfEducation === 'Highschool/GED' || levelOfEducation === 'AA' || levelOfEducation === 'BA or Higher') && (inSchool === 'true' || inSchool === true)
        ? showDiv : hidden
        let showC = (levelOfEducation === 'No Highschool / Some Highschool')  && (inSchool === 'false' || inSchool === false) ? showDiv : hidden
```

**Comment by techhire-la** [comment]
Excellent coding @BeatrizTovar!  I've added your code but updated a few things.

## Your Added code 
- Adding an answered state
```
    state = {
        answered: false
    }
```

- your handleNext addition using answered state
```
    handleNext = (e, { id }) => {
        let answered = this.state.answered;
        if (answered) {

            var nextQuestion = parseInt(e.target.parentNode.id)
            var addOne = (nextQuestion + 1).toString();

            this.setState({ questionNumber: addOne, answered: !answered })
        }
        else {
            alert(`${"Question "}${this.state.questionNumber}${" not answered"}`)
        }

    }
```

- your handleBack addition using answered state
```
    handleBack = (e, { id }) => {
        let answered = this.state.answered;
        var lastQuestion = parseInt(e.target.parentNode.id)
        var subtractOne = (lastQuestion - 1).toString();

        this.setState({ questionNumber: subtractOne, answered: !answered})
```

## Updated
In the  ```this.setState``` of handleBack and handleNext, I changed the hardcoding of state from true to false to:
```
this.setState({ questionNumber: addOne, answered: !answered })
```
This ```!answered``` makes the boolean value more flexible when moving back and then hitting next.  

## Bug
Initially, if I selected back and then hit next, despite the question being answered, the state of answered would not have switched and  I would get the alert that I had not answered the question.  ```!answered``` currently fixes that problem.  However, if I go to far back and then try to go forward, I essentially hit the same problem.  Not a huge issue, but one to try to refactor and work out.
